/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2-dev */

#ifndef PB_DAGR_PB_H_INCLUDED
#define PB_DAGR_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(230) ChatMessage_message_t;
typedef struct _ChatMessage {
    int32_t from;
    int32_t to;
    ChatMessage_message_t message;
} ChatMessage;

typedef struct _DagrPacket {
    int32_t packet_num;
    pb_callback_t fragment;
    uint32_t rx_time;
} DagrPacket;


/* Initializer values for message structs */
#define ChatMessage_init_default                 {0, 0, {0, {0}}}
#define DagrPacket_init_default                  {0, {{NULL}, NULL}, 0}
#define ChatMessage_init_zero                    {0, 0, {0, {0}}}
#define DagrPacket_init_zero                     {0, {{NULL}, NULL}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ChatMessage_from_tag                     1
#define ChatMessage_to_tag                       2
#define ChatMessage_message_tag                  3
#define DagrPacket_packet_num_tag                1
#define DagrPacket_fragment_tag                  3
#define DagrPacket_rx_time_tag                   4

/* Struct field encoding specification for nanopb */
#define ChatMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    from,              1) \
X(a, STATIC,   SINGULAR, INT32,    to,                2) \
X(a, STATIC,   SINGULAR, BYTES,    message,           3)
#define ChatMessage_CALLBACK NULL
#define ChatMessage_DEFAULT NULL

#define DagrPacket_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    packet_num,        1) \
X(a, CALLBACK, SINGULAR, BYTES,    fragment,          3) \
X(a, STATIC,   SINGULAR, UINT32,   rx_time,           4)
#define DagrPacket_CALLBACK pb_default_field_callback
#define DagrPacket_DEFAULT NULL

extern const pb_msgdesc_t ChatMessage_msg;
extern const pb_msgdesc_t DagrPacket_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ChatMessage_fields &ChatMessage_msg
#define DagrPacket_fields &DagrPacket_msg

/* Maximum encoded size of messages (where known) */
#define ChatMessage_size                         255
/* DagrPacket_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
