/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2-dev */

#include "dagr.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ChatMessage, ChatMessage, AUTO)


PB_BIND(DagrPacket, DagrPacket, AUTO)



