/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.1 */

#ifndef PB_DAGR_PB_H_INCLUDED
#define PB_DAGR_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _MessagePacket {
    int32_t from;
    int32_t to;
    pb_callback_t payload;
    uint32_t rx_time;
} MessagePacket;

typedef struct _fromDagr {
    bool has_packet;
    MessagePacket packet;
} fromDagr;

typedef struct _toDagr {
    pb_size_t which_variant;
    union {
        MessagePacket packet;
    } variant;
} toDagr;


/* Initializer values for message structs */
#define MessagePacket_init_default               {0, 0, {{NULL}, NULL}, 0}
#define toDagr_init_default                      {0, {MessagePacket_init_default}}
#define fromDagr_init_default                    {false, MessagePacket_init_default}
#define MessagePacket_init_zero                  {0, 0, {{NULL}, NULL}, 0}
#define toDagr_init_zero                         {0, {MessagePacket_init_zero}}
#define fromDagr_init_zero                       {false, MessagePacket_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define MessagePacket_from_tag                   1
#define MessagePacket_to_tag                     2
#define MessagePacket_payload_tag                3
#define MessagePacket_rx_time_tag                4
#define fromDagr_packet_tag                      1
#define toDagr_packet_tag                        1

/* Struct field encoding specification for nanopb */
#define MessagePacket_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    from,              1) \
X(a, STATIC,   SINGULAR, INT32,    to,                2) \
X(a, CALLBACK, SINGULAR, BYTES,    payload,           3) \
X(a, STATIC,   SINGULAR, UINT32,   rx_time,           4)
#define MessagePacket_CALLBACK pb_default_field_callback
#define MessagePacket_DEFAULT NULL

#define toDagr_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (variant,packet,variant.packet),   1)
#define toDagr_CALLBACK NULL
#define toDagr_DEFAULT NULL
#define toDagr_variant_packet_MSGTYPE MessagePacket

#define fromDagr_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  packet,            1)
#define fromDagr_CALLBACK NULL
#define fromDagr_DEFAULT NULL
#define fromDagr_packet_MSGTYPE MessagePacket

extern const pb_msgdesc_t MessagePacket_msg;
extern const pb_msgdesc_t toDagr_msg;
extern const pb_msgdesc_t fromDagr_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MessagePacket_fields &MessagePacket_msg
#define toDagr_fields &toDagr_msg
#define fromDagr_fields &fromDagr_msg

/* Maximum encoded size of messages (where known) */
/* MessagePacket_size depends on runtime parameters */
/* toDagr_size depends on runtime parameters */
/* fromDagr_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
