/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "dagr.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MessagePacket, MessagePacket, AUTO)


PB_BIND(toDagr, toDagr, AUTO)


PB_BIND(fromDagr, fromDagr, AUTO)



